#!/bin/sh

IPTABLES=/usr/sbin/iptables

#创建一个命名为internet链，主要在此链上处理
$IPTABLES -N internet -t mangle

$IPTABLES -t mangle -A PREROUTING -j internet

#从文件中导入放行的用户mac地址
awk 'BEGIN { FS="\t"; } { system("$IPTABLES -t mangle -A internet -m mac --mac-source "$1" -j RETURN"); }' /usr/tgrass/trustmac

#例外，因为app会访问i.tgrass.com的2060端口
$IPTABLES -t mangle -A internet -p tcp --dport 2060 -d 218.244.131.138 -j MARK --set-mark 99
#从文件中导入放行的ip地址
awk 'BEGIN { FS="\t"; } { system("$IPTABLES -t mangle -A internet -d "$1" -j RETURN"); }' /usr/tgrass/trustip

# 未在放行的mac地址列表中的话，打标记为99
$IPTABLES -t mangle -A internet -j MARK --set-mark 99
################################

# 重定向
$IPTABLES -t nat -N unkownnat
$IPTABLES -t nat -A PREROUTING -m mark --mark 99 -j unkownnat
$IPTABLES -t nat -A unkownnat -p tcp --dport 80 -j REDIRECT --to-port 80
$IPTABLES -t nat -A unkownnat -p tcp --dport 2060 -j REDIRECT --to-port 80

# 对于标记为99创建一个链
$IPTABLES -t filter -N unkownfilter
$IPTABLES -t filter -A FORWARD -m mark --mark 99 -j unkownfilter
$IPTABLES -t filter -A unkownfilter  -p tcp --dport 53 -j ACCEPT
$IPTABLES -t filter -A unkownfilter  -p udp --dport 53 -j ACCEPT
$IPTABLES -t filter -A unkownfilter  -p tcp --dport 67 -j ACCEPT
$IPTABLES -t filter -A unkownfilter  -p udp --dport 67 -j ACCEPT
$IPTABLES -t filter -A unkownfilter  -j REJECT --reject-with icmp-port-unreachable
